version: '2'
services:
    postgres:
        image: postgres
	volum?

    taigaback:
        image: ipedrazas/taiga-back
        links:
            - postgres:postgres

    taigafront:
        image: ipedrazas/taiga-front
        links:
            - taiga-back:taiga-back
        environment:
            - "API_NAME=https://taiga.pisys.eu:8888"
            - "VIRTUAL_HOST=taiga.pisys.eu"
